spring:
  application:
    name: api-getway
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: info
    com.eureka.client.api.getway: debug


