spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product_services
      username: productsuper
      password: super123
      repositories:
        enabled: true
  application:
    name: product-services
server:
  port: 8091
  servlet:
    context-path: /products


eureka:
 client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#      uri: mongodb://productsuper:super123@localhost:27017/product_services
# mongodb uri format
#  mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
#